<?xml version="1.0" encoding="UTF-8"?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is JAX-WS RI 2.2.8 svn-revision#13980. --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://sim.aravo.com/datamodel/2013/01/domainobjects" xmlns:ns2="http://sim.aravo.com/datamodel/2012/08/lists" xmlns:ns3="http://sim.aravo.com/datamodel/2013/01/links" xmlns:tns="http://sim.aravo.com/soapservices/v4_2/SupplierContactService" targetNamespace="http://sim.aravo.com/soapservices/v4_2/SupplierContactService" version="1.0">

<xs:import namespace="http://sim.aravo.com/datamodel/2013/01/domainobjects" schemaLocation="ContactXSD4.xsd"/>

<xs:import namespace="http://sim.aravo.com/datamodel/2012/08/lists" schemaLocation="ContactXSD5.xsd"/>

<xs:import namespace="http://sim.aravo.com/datamodel/2013/01/links" schemaLocation="ContactXSD3.xsd"/>

<xs:element name="createSupplierContacts" type="tns:createSupplierContacts"/>

<xs:element name="createSupplierContactsResponse" type="tns:createSupplierContactsResponse"/>

<xs:element name="deactivateSupplierContacts" type="tns:deactivateSupplierContacts"/>

<xs:element name="deactivateSupplierContactsResponse" type="tns:deactivateSupplierContactsResponse"/>

<xs:element name="findSupplierContactAuditRecords" type="tns:findSupplierContactAuditRecords"/>

<xs:element name="findSupplierContactAuditRecordsResponse" type="tns:findSupplierContactAuditRecordsResponse"/>

<xs:element name="getActiveSupplierContactIds" type="tns:getActiveSupplierContactIds"/>

<xs:element name="getActiveSupplierContactIdsResponse" type="tns:getActiveSupplierContactIdsResponse"/>

<xs:element name="getFields" type="tns:getFields"/>

<xs:element name="getFieldsResponse" type="tns:getFieldsResponse"/>

<xs:element name="getSupplierContacts" type="tns:getSupplierContacts"/>

<xs:element name="getSupplierContacts2" type="tns:getSupplierContacts2"/>

<xs:element name="getSupplierContacts2Response" type="tns:getSupplierContacts2Response"/>

<xs:element name="getSupplierContactsResponse" type="tns:getSupplierContactsResponse"/>

<xs:element name="updateSupplierContacts" type="tns:updateSupplierContacts"/>

<xs:element name="updateSupplierContactsResponse" type="tns:updateSupplierContactsResponse"/>

<xs:element name="upsertSupplierContacts" type="tns:upsertSupplierContacts"/>

<xs:element name="upsertSupplierContactsResponse" type="tns:upsertSupplierContactsResponse"/>

<xs:complexType name="upsertSupplierContacts">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="upsertRequest" nillable="true" type="tns:upsertRequest"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="upsertRequest">
<xs:complexContent>
<xs:extension base="tns:updateRequest">
<xs:sequence/>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType name="updateRequest">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="fields" nillable="true" type="tns:field"/>
<xs:element minOccurs="0" name="pid" type="xs:string"/>
<xs:element minOccurs="0" name="pidType" type="xs:string"/>
<xs:element minOccurs="0" name="sid" type="xs:string"/>
<xs:element minOccurs="0" name="sidType" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="field">
<xs:sequence>
<xs:element name="name" type="xs:string"/>
<xs:element name="type" type="xs:string"/>
<xs:element maxOccurs="unbounded" name="values" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="upsertSupplierContactsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="tns:response"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="response">
<xs:complexContent>
<xs:extension base="tns:indexedResponse">
<xs:sequence>
<xs:element minOccurs="0" name="pid" type="xs:string"/>
<xs:element minOccurs="0" name="pidType" type="xs:string"/>
<xs:element minOccurs="0" name="sid" type="xs:string"/>
<xs:element minOccurs="0" name="sidType" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType name="indexedResponse">
<xs:complexContent>
<xs:extension base="tns:simpleResponse">
<xs:sequence>
<xs:element name="index" type="xs:int"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType name="simpleResponse">
<xs:sequence>
<xs:element minOccurs="0" name="message" type="xs:string"/>
<xs:element name="status" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="faultBean">
<xs:sequence>
<xs:element minOccurs="0" name="message" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getFields">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="getFieldsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getSupplierContacts">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="request" nillable="true" type="tns:getRequest"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getRequest">
<xs:sequence>
<xs:element minOccurs="0" name="supplierContactId" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getSupplierContactsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="tns:getResponse"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getResponse">
<xs:complexContent>
<xs:extension base="tns:indexedResponse">
<xs:sequence>
<xs:element minOccurs="0" name="supplierContact" type="tns:supplierContact"/>
<xs:element minOccurs="0" name="supplierId" type="xs:int"/>
<xs:element minOccurs="0" name="supplierIdentifier" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType name="supplierContact">
<xs:sequence>
<xs:element minOccurs="0" name="id" type="xs:int"/>
<xs:element name="active" type="xs:boolean"/>
<xs:element minOccurs="0" name="username" type="xs:string"/>
<xs:element minOccurs="0" name="firstname" type="xs:string"/>
<xs:element minOccurs="0" name="middlename" type="xs:string"/>
<xs:element minOccurs="0" name="lastname" type="xs:string"/>
<xs:element minOccurs="0" name="title" type="xs:string"/>
<xs:element minOccurs="0" name="email" type="xs:string"/>
<xs:element minOccurs="0" name="address" type="ns1:address"/>
<xs:element minOccurs="0" name="officePhone" type="ns1:phone"/>
<xs:element minOccurs="0" name="mobilePhone" type="ns1:phone"/>
<xs:element minOccurs="0" name="fax" type="ns1:phone"/>
<xs:element minOccurs="0" name="timeZone" type="xs:string"/>
<xs:element minOccurs="0" name="perspective" type="xs:string"/>
<xs:element maxOccurs="unbounded" minOccurs="0" name="supplierContactTypes" nillable="true" type="ns2:listItem"/>
<xs:element maxOccurs="unbounded" minOccurs="0" name="linkedEntities" nillable="true" type="ns3:compositionLink"/>
<xs:element maxOccurs="unbounded" minOccurs="0" name="linkedLocations" nillable="true" type="ns3:compositionLink"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="updateSupplierContacts">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="updateRequest" nillable="true" type="tns:updateRequest"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="updateSupplierContactsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="tns:response"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="deactivateSupplierContacts">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="request" nillable="true" type="tns:deactivateRequest"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="deactivateRequest">
<xs:sequence>
<xs:element minOccurs="0" name="pid" type="xs:string"/>
<xs:element minOccurs="0" name="pidType" type="xs:string"/>
<xs:element minOccurs="0" name="sid" type="xs:string"/>
<xs:element minOccurs="0" name="sidType" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="deactivateSupplierContactsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="tns:response"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="createSupplierContacts">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="createRequest" nillable="true" type="tns:createRequest"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="createRequest">
<xs:sequence>
<xs:element maxOccurs="unbounded" name="fields" type="tns:field"/>
<xs:element name="sid" nillable="true" type="xs:string"/>
<xs:element name="sidType" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="createSupplierContactsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="tns:response"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getSupplierContacts2">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="request" nillable="true" type="tns:getRequest2"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getRequest2">
<xs:sequence>
<xs:element minOccurs="0" name="pid" type="xs:string"/>
<xs:element minOccurs="0" name="pidType" type="xs:string"/>
<xs:element minOccurs="0" name="sid" type="xs:string"/>
<xs:element minOccurs="0" name="sidType" type="xs:string"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getSupplierContacts2Response">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="tns:getResponse2"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="getResponse2">
<xs:complexContent>
<xs:extension base="tns:indexedResponse">
<xs:sequence>
<xs:element minOccurs="0" name="supplierContact" type="tns:supplierContact2"/>
<xs:element minOccurs="0" name="supplierId" type="xs:int"/>
<xs:element minOccurs="0" name="supplierIdentifier" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType name="supplierContact2">
<xs:complexContent>
<xs:extension base="tns:supplierContact">
<xs:sequence>
<xs:element minOccurs="0" name="externalUsername" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType name="getActiveSupplierContactIds">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="getActiveSupplierContactIdsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="r" nillable="true" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="findSupplierContactAuditRecords">
<xs:sequence>
<xs:element minOccurs="0" name="from" type="xs:dateTime"/>
<xs:element minOccurs="0" name="to" type="xs:dateTime"/>
<xs:element maxOccurs="unbounded" minOccurs="0" name="option" nillable="true" type="ns1:option"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="findSupplierContactAuditRecordsResponse">
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="tns:supplierContactAuditRecord"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="supplierContactAuditRecord">
<xs:complexContent>
<xs:extension base="tns:baseSupplierAuditRecord">
<xs:sequence>
<xs:element minOccurs="0" name="personId" type="xs:long"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType abstract="true" name="baseSupplierAuditRecord">
<xs:complexContent>
<xs:extension base="tns:universalAuditRecord">
<xs:sequence>
<xs:element minOccurs="0" name="locationId" type="xs:long"/>
<xs:element minOccurs="0" name="locationIdentifier" type="xs:string"/>
<xs:element minOccurs="0" name="supplierId" type="xs:long"/>
<xs:element minOccurs="0" name="supplierIdentifier" type="xs:string"/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>

<xs:complexType abstract="true" name="universalAuditRecord">
<xs:sequence>
<xs:element minOccurs="0" name="flag" type="xs:string"/>
<xs:element minOccurs="0" name="timestamp" type="xs:dateTime"/>
<xs:element minOccurs="0" name="uaeId" type="xs:long"/>
</xs:sequence>
</xs:complexType>
</xs:schema>